 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Engrampa Archive Manager", "engrampa ", "/usr/share/icons/hicolor/16x16/apps/engrampa.png" },
     {"Fern Wifi Cracker", "gksu fern-wifi-cracker", "///usr/share/fern-wifi-cracker/resources/screen_splash.png" },
     {"GTKWave", "gtkwave", "/usr/share/icons/gnome/16x16/mimetypes/gtkwave.png" },
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Guymager", "/usr/bin/guymager", "/usr/share/pixmaps/guymager.png" },
     {"Johnny", "johnny", "/usr/share/pixmaps/johnny.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Metasploit AV Evasion", "xterm -e metasploitavevasion"},
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"Pip3line", "pip3line", "///usr/share/icons/hicolor/128x128/apps/pip3line.png" },
     {"Pluma", "pluma ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Redshift", "redshift-gtk"},
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Xarchiver", "xarchiver ", "/usr/share/icons/hicolor/16x16/apps/xarchiver.png" },
     {"gpa", "gpa", "/usr/share/pixmaps/gpa.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Cantor", "cantor  -qwindowtitle Cantor ", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"FreeCAD", "/usr/bin/freecad ", "///usr/share/freecad/freecad.xpm" },
     {"GNU Octave", "/usr/bin/octave --force-gui ", "/usr/share/icons/hicolor/16x16/apps/octave.png" },
     {"LeoCAD", "leocad "},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Qucs", "qucs ", "/usr/share/icons/hicolor/16x16/apps/qucs.png" },
     {"Stellarium", "stellarium", "/usr/share/icons/hicolor/16x16/apps/stellarium.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"0 A.D.", "0ad", "/usr/share/pixmaps/0ad.png" },
     {"Extreme Tux Racer", "etr", "/usr/share/pixmaps/etr.png" },
     {"PlayOnLinux", "playonlinux", "///usr/share/playonlinux/etc/playonlinux.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"VBA-M", "visualboyadvance-m-wx ", "/usr/share/icons/hicolor/16x16/apps/vbam.png" },
     {"mGBA", "mgba-qt ", "/usr/share/icons/hicolor/16x16/apps/mgba.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Blender", "blender ", "/usr/share/icons/hicolor/16x16/apps/blender.png" },
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gpick", "gpick", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/calligrakrita.png" },
     {"LeoCAD", "leocad "},
     {"LibreCAD", "librecad ", "/usr/share/icons/hicolor/16x16/apps/librecad.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"OpenSCAD", "openscad ", "/usr/share/pixmaps/openscad.png" },
     {"Pinta", "pinta ", "/usr/share/icons/hicolor/16x16/apps/pinta.png" },
     {"QCAD", "qcad ", "/usr/share/pixmaps/qcad_icon.png" },
     {"Scribus", "scribus ", "/usr/share/icons/hicolor/32x32/apps/scribus.png" },
     {"Viewnior", "viewnior ", "/usr/share/icons/hicolor/16x16/apps/viewnior.png" },
     {"sK1 illustration program", "sk1 ", "/usr/share/pixmaps/sk1.png" },
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Amap", "amap"},
     {"Angry IP Scanner", "ipscan"},
     {"Apache Directory Studio", "/opt/ApacheDirectoryStudio/ApacheDirectoryStudio", "///opt/ApacheDirectoryStudio/features/org.apache.directory.studio.ldapbrowser.feature_2.0.0.v20161101-M12/studio.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Claws Mail", "claws-mail ", "/usr/share/icons/hicolor/48x48/apps/claws-mail.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Gajim", "gajim", "/usr/share/icons/hicolor/64x64/apps/gajim.png" },
     {"Google Earth", "/opt/google/earth/free/google-earth ", "/usr/share/icons/hicolor/16x16/apps/google-earth.png" },
     {"Gqrx", "gqrx", "/usr/share/pixmaps/gqrx.svg" },
     {"Kismon", "kismon", "/usr/share/icons/gnome/16x16/devices/network-wireless.png" },
     {"Konqueror", "konqueror", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"OnionShare", "/usr/bin/onionshare-gui", "///usr/share/pixmaps/onionshare80.xpm" },
     {"Opera", "opera ", "/usr/share/icons/hicolor/16x16/apps/opera.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"SeaMonkey internet suite", "seamonkey", "/usr/share/pixmaps/seamonkey.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamViewer 12", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/48x48/apps/teamviewer.png" },
     {"Thunderbird", "/usr/lib/thunderbird/thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"TigerVNC Viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"Vivaldi", "/usr/bin/vivaldi-stable ", "/usr/share/icons/hicolor/16x16/apps/vivaldi.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XSSer", "/usr/bin/xsser --gtk --silent", "///usr/share/xsser/gtk/images/xssericon_24x24.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Adobe Reader 9", "acroread ", "/usr/share/pixmaps/acroread.png" },
     {"GnuCash", "gnucash ", "/usr/share/icons/hicolor/16x16/apps/gnucash-icon.png" },
     {"Hibiscus", "jameica", "///opt/jameica/plugins/hibiscus/icons/hibiscus-icon-64x64.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"PDF-Shuffler", "pdfshuffler", "/usr/share/pixmaps/pdfshuffler.png" },
     {"ReText", "retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"ePDFViewer", "epdfview ", "/usr/share/icons/hicolor/24x24/apps/epdfview.png" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Argtable", "argtable"},
     {"Cuckoo", "/usr/bin/cuckoo"},
     {"umongo", "/usr/bin/umongo.sh", "///usr/share/pixmaps/umongo.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Arduino IDE", "arduino ", "/usr/share/icons/hicolor/16x16/apps/arduino.png" },
     {"Autodesk EAGLE", "eagle ", "/usr/share/pixmaps/eagle.png" },
     {"Bitmap to Component Converter", "bitmap2component", "/usr/share/icons/hicolor/48x48/apps/bitmap2component.png" },
     {"CLion", "\"/usr/bin/clion\" ", "/usr/share/pixmaps/clion.svg" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"CvPcb", "cvpcb", "/usr/share/icons/hicolor/48x48/apps/cvpcb.png" },
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"Database browser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"Eeschema", "eeschema ", "/usr/share/icons/hicolor/48x48/apps/eeschema.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Energia", "energia", "/usr/share/pixmaps/energia.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"GHex", "ghex ", "/usr/share/icons/hicolor/16x16/apps/ghex.png" },
     {"GRC", "gnuradio-companion "},
     {"GerbView", "gerbview", "/usr/share/icons/hicolor/48x48/apps/gerbview.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"IntelliJ IDEA Community Edition", "idea.sh ", "/usr/share/pixmaps/idea.png" },
     {"KDevelop", "kdevelop ", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDevelop (Pick Session)", "kdevelop --ps", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KiCad", "kicad ", "/usr/share/icons/hicolor/22x22/apps/kicad.png" },
     {"LiteIDE", "liteide", "/usr/share/pixmaps/liteide.png" },
     {"MonoDevelop", "monodevelop ", "/usr/share/icons/hicolor/16x16/apps/monodevelop.png" },
     {"MySQL Workbench", "mysql-workbench ", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"NetBeans", "netbeans ", "/usr/share/pixmaps/netbeans.png" },
     {"Pcb Calculator", "pcb_calculator", "/usr/share/icons/hicolor/48x48/apps/pcbcalculator.png" },
     {"Pcbnew", "pcbnew ", "/usr/share/icons/hicolor/48x48/apps/pcbnew.png" },
     {"Processing", "processing", "/usr/share/pixmaps/processing.png" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"SQLite database browser", "sqlitebrowser", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"ZeroBrane Studio", "zbstudio ", "/usr/share/icons/hicolor/16x16/apps/zbstudio.png" },
     {"edb", "edb"},
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"regexxer Search Tool", "regexxer", "/usr/share/icons/hicolor/48x48/apps/regexxer.png" },
     {"wxGlade", "wxglade ", "/usr/share/pixmaps/wxglade.png" },
     {"wxLua Editor", "wxluaedit "},
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"QCAD", "qcad ", "/usr/share/pixmaps/qcad_icon.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Kaffeine", "kaffeine "},
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Spotify", "spotify ", "/usr/share/pixmaps/spotify-client.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Arch-Wiki", "xterm -e arch-wiki", "/usr/share/pixmaps/archlinux.png" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Dolphin", "dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XSSer", "/usr/bin/xsser --gtk --silent", "///usr/share/xsser/gtk/images/xssericon_24x24.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

