accessoriesmenu = {
    { "calculator", "/usr/bin/galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
    { "cr3", "/usr/bin/cr3", "/usr/share/pixmaps/cr3.png" },
    { "emacs", "/usr/bin/emacs", "/usr/share/icons/hicolor/scalable/apps/emacs.svg" },
    { "engrampa", "/usr/bin/engrampa", "/usr/share/icons/hicolor/32x32/apps/engrampa.png" },
    { "ghex", "/usr/bin/ghex ", "/usr/share/icons/hicolor/48x48/apps/ghex.png" },
    { "gnu privacy agent", "/usr/bin/gpa", "/usr/share/pixmaps/gpa.png" },
    { "gscriptor", "/usr/bin/gscriptor", "/usr/share/icons/hicolor/48x48/apps/gcr-smart-card.png" },
    { "gvim", "/usr/bin/gvim", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
    { "kleopatra", "/usr/bin/kleopatra", "/usr/share/icons/hicolor/48x48/apps/kleopatra.png" },
    { "pluma", "/usr/bin/pluma", "/usr/share/icons/Adwaita/48x48/apps/accessories-text-editor.png" },
    { "regexxer", "/usr/bin/regexxer", "/usr/share/icons/hicolor/48x48/apps/regexxer.png" },
    { "retext", "/usr/bin/retext", "/usr/share/icons/hicolor/48x48/apps/retext.png" },
    { "seahorse", "/usr/bin/seahorse", "/usr/share/icons/hicolor/48x48/apps/seahorse.png" },
    { "vim", terminal.." -e /usr/bin/vim", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
    { "xarchiver", "xarchiver", "/usr/share/icons/hicolor/48x48/apps/xarchiver.png" },
}
dbmenu = {
    { "dbeaver", "/usr/bin/dbeaver", "/usr/share/icons/hicolor/48x48/apps/dbeaver.xpm" },
    { "mysql workbench", "/usr/bin/mysql-workbench", "/usr/share/icons/hicolor/48x48/apps/mysql-workbench.png" },
    { "sql workbench", "/usr/bin/sqlworkbench", "/usr/share/icons/hicolor/32x32/apps/workbench32.png" },
    { "sqlitebrowser", "/usr/bin/sqlitebrowser", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
    { "umongo", "/usr/bin/umongo.sh", "/usr/share/pixmaps/umongo.png" },
}
developmentmenu = {
    { "android studio", "/usr/bin/android-studio ", "/usr/share/pixmaps/android-studio.png" },
    { "anjuta", "/usr/bin/anjuta", "/usr/share/icons/hicolor/48x48/apps/anjuta.png" },
    { "clion", "/usr/bin/clion", "/usr/share/pixmaps/clion.svg" },
    { "ddd", "/usr/bin/ddd", "/usr/share/pixmaps/ddd.xpm" },
    { "eclipse", "/usr/bin/eclipse", "/usr/share/icons/hicolor/48x48/apps/eclipse.png" },
    { "glade gtk2", "/usr/bin/glade-3", "/usr/share/icons/hicolor/48x48/apps/glade-3.png" },
    { "glade gtk3", "/usr/bin/glade ", "/usr/share/icons/hicolor/48x48/apps/glade.png" },
    { "intellij", "/usr/bin/idea.sh", "/usr/share/pixmaps/idea.png" },
    { "kdevelop", "/usr/bin/kdevelop", "/usr/share/icons/hicolor/48x48/apps/kdevelop.png" },
    { "lazarus", "/usr/bin/lazarus", "/usr/lib/lazarus/images/ide_icon48x48.png" },
    { "liteide", "/usr/bin/liteide", "/usr/share/pixmaps/liteide.png" },
    { "monodevelop", "/usr/bin/monodevelop", "/usr/share/icons/hicolor/48x48/apps/monodevelop.png" },
    { "netbeans", "/usr/bin/netbeans -J-Xmx4096m", "/usr/share/pixmaps/netbeans.png" },
    { "qgit", "/usr/bin/qgit", "/usr/share/icons/hicolor/48x48/apps/qgit.png" },
    { "qtcreator", "/usr/bin/qtcreator", "/usr/share/icons/hicolor/48x48/apps/QtProject-qtcreator.png" },
    { "tortoisehg", "/usr/bin/thg", "/usr/share/pixmaps/thg_logo.svg" },
    { "wxglade", "/usr/bin/wxglade", "/usr/share/pixmaps/wxglade.png" },
    { "zbstudio", "/usr/bin/zbstudio", "/usr/share/icons/hicolor/48x48/apps/zbstudio.png" },
}
engineeringmenu = {
    { "arduino", "/usr/bin/arduino", "/usr/share/icons/hicolor/48x48/apps/arduino.png" },
    { "eagle", "/home/hanez/bin/eagle", "/usr/share/pixmaps/eagle.png" },
    { "energia", "/usr/bin/energia", "/usr/share/pixmaps/energia.png" },
    { "freecad", "/usr/bin/freecad", "/usr/share/freecad/freecad-icon-48.png" },
    { "fritzing", "/usr/bin/Fritzing", "/usr/share/icons/fritzing.png" },
    { "kicad", "/usr/bin/kicad", "/usr/share/icons/hicolor/48x48/apps/kicad.png" },
    { "leocad", "/usr/bin/leocad", "/usr/share/icons/hicolor/scalable/mimetypes/application-vnd.leocad.svg" },
    { "librecad", "/usr/bin/librecad", "/usr/share/icons/hicolor/scalable/apps/librecad.svg" },
    { "openscad", "/usr/bin/openscad", "/usr/share/pixmaps/openscad.png" },
    { "processing", "/usr/bin/processing", "/usr/share/pixmaps/processing.png" },
    { "qcad", "/usr/bin/qcad", "/usr/share/pixmaps/qcad_icon.png" },
    { "qucs", "/usr/bin/qucs", "/usr/share/icons/hicolor/48x48/apps/qucs.png" },
}
puzzlesmenu = {
    { "blackbox", "/usr/bin/puzzles-blackbox", "/usr/share/icons/hicolor/48x48/apps/blackbox.png" },
    { "bridges", "/usr/bin/bridges", "/usr/share/icons/hicolor/48x48/apps/bridges.png" },
    { "cube", "/usr/bin/puzzles-cube", "/usr/share/icons/hicolor/48x48/apps/cube.png" },
    { "dominosa", "/usr/bin/dominosa", "/usr/share/icons/hicolor/48x48/apps/dominosa.png" },
    { "fifteen", "/usr/bin/fifteen", "/usr/share/icons/hicolor/48x48/apps/fifteen.png" },
    { "filling", "/usr/bin/filling", "/usr/share/icons/hicolor/48x48/apps/filling.png" },
    { "flip", "/usr/bin/flip", "/usr/share/icons/hicolor/48x48/apps/flip.png" },
    { "flood", "/usr/bin/flood", "/usr/share/icons/hicolor/48x48/apps/flood.png" },
    { "galaxies", "/usr/bin/galaxies", "/usr/share/icons/hicolor/48x48/apps/galaxies.png" },
    { "guess", "/usr/bin/guess", "/usr/share/icons/hicolor/48x48/apps/guess.png" },
    { "inertia", "/usr/bin/inertia", "/usr/share/icons/hicolor/48x48/apps/inertia.png" },
    { "keen", "/usr/bin/keen", "/usr/share/icons/hicolor/48x48/apps/keen.png" },
    { "lightup", "/usr/bin/lightup", "/usr/share/icons/hicolor/48x48/apps/lightup.png" },
    { "loopy", "/usr/bin/loopy", "/usr/share/icons/hicolor/48x48/apps/loopy.png" },
    { "magnets", "/usr/bin/magnets", "/usr/share/icons/hicolor/48x48/apps/magnets.png" },
    { "maps", "/usr/bin/maps", "/usr/share/icons/hicolor/48x48/apps/map.png" },
    { "mines", "/usr/bin/mines", "/usr/share/icons/hicolor/48x48/apps/mines.png" },
    { "net", "/usr/bin/puzzles-net", "/usr/share/icons/hicolor/48x48/apps/net.png" },
    { "netslide", "/usr/bin/netslide", "/usr/share/icons/hicolor/48x48/apps/netslide.png" },
    { "palisade", "/usr/bin/palisade", "/usr/share/icons/hicolor/48x48/apps/palisade.png" },
    { "pattern", "/usr/bin/pattern", "/usr/share/icons/hicolor/48x48/apps/pattern.png" },
    { "pearl", "/usr/bin/pearl", "/usr/share/icons/hicolor/48x48/apps/pearl.png" },
    { "pegs", "/usr/bin/pegs", "/usr/share/icons/hicolor/48x48/apps/pegs.png" },
    { "range", "/usr/bin/range", "/usr/share/icons/hicolor/48x48/apps/range.png" },
    { "rect", "/usr/bin/rect", "/usr/share/icons/hicolor/48x48/apps/rect.png" },
    { "samegame", "/usr/bin/samegame", "/usr/share/icons/hicolor/48x48/apps/samegame.png" },
    { "signpost", "/usr/bin/signpost", "/usr/share/icons/hicolor/48x48/apps/signpost.png" },
    { "singles", "/usr/bin/singles", "/usr/share/icons/hicolor/48x48/apps/singles.png" },
    { "sixteen", "/usr/bin/sixteen", "/usr/share/icons/hicolor/48x48/apps/sixteen.png" },
    { "slant", "/usr/bin/slant", "/usr/share/icons/hicolor/48x48/apps/slant.png" },
    { "solo", "/usr/bin/solo", "/usr/share/icons/hicolor/48x48/apps/solo.png" },
    { "tents", "/usr/bin/tents", "/usr/share/icons/hicolor/48x48/apps/tents.png" },
    { "towers", "/usr/bin/towers", "/usr/share/icons/hicolor/48x48/apps/towers.png" },
    { "tracks", "/usr/bin/tracks", "/usr/share/icons/hicolor/48x48/apps/tracks.png" },
    { "twiddle", "/usr/bin/twiddle", "/usr/share/icons/hicolor/48x48/apps/twiddle.png" },
    { "undead", "/usr/bin/undead", "/usr/share/icons/hicolor/48x48/apps/undead.png" },
    { "unequal", "/usr/bin/unequal", "/usr/share/icons/hicolor/48x48/apps/unequal.png" },
    { "unruly", "/usr/bin/unruly", "/usr/share/icons/hicolor/48x48/apps/unruly.png" },
    { "untangle", "/usr/bin/untangle", "/usr/share/icons/hicolor/48x48/apps/untangle.png" },
}
gamesmenu = {
    { "puzzles", puzzlesmenu, "/usr/share/icons/matefaenza/categories/scalable/applications-puzzles.svg" },
    { "0 a.d.", "/usr/bin/0ad", "/usr/share/pixmaps/0ad.png" },
    { "emulationstation", "/usr/bin/emulationstation", "/usr/share/pixmaps/retroarch.svg" },
    { "steam", "/usr/bin/steam", "/usr/share/pixmaps/steam.png" },
}
graphicsmenu = {
    { "blender", "/usr/bin/blender", "/usr/share/icons/hicolor/48x48/apps/blender.png" },
    { "font manager", "/usr/bin/font-manager", "/usr/share/icons/gnome/48x48/apps/preferences-desktop-font.png" },
    { "gimp", "/usr/bin/gimp", "/usr/share/icons/hicolor/48x48/apps/gimp.png" },
    { "gpick", "/usr/bin/gpick", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
    { "image scan!", "/usr/bin/iscan", "/usr/share/icons/gnome/48x48/devices/scanner.png" },
    { "inkscape", "/usr/bin/inkscape", "/usr/share/icons/hicolor/48x48/apps/inkscape.png" },
    { "krita", "/usr/bin/krita", "/usr/share/icons/hicolor/48x48/apps/calligrakrita.png" },
    { "pinta", "/usr/bin/pinta", "/usr/share/pixmaps/pinta.xpm" },
    { "scribus", "/usr/bin/scribus", "/usr/share/icons/hicolor/32x32/apps/scribus.png" },
    { "sk1", "/usr/bin/sk1", "/usr/share/pixmaps/sk1.png" },
    { "viewnior", "/usr/bin/viewnior", "/usr/share/icons/hicolor/48x48/apps/viewnior.png" },
    { "xsane scanning", "/usr/bin/xsane", "/usr/share/pixmaps/xsane.xpm" },
}
internetmenu = {
    { "chromium", "/usr/bin/chromium", "/usr/share/icons/hicolor/48x48/apps/chromium.png" },
    { "claws", "/usr/bin/claws-mail", "/usr/share/icons/hicolor/48x48/apps/claws-mail.png" },
    { "firefox", "/usr/bin/firefox", "/usr/share/icons/hicolor/48x48/apps/firefox.png" },
    { "franz", "/usr/bin/franz-bin", "/usr/share/pixmaps/franz.png" },
    { "gftp", "/usr/bin/gftp", "/usr/share/pixmaps/gftp.png" },
    { "google chrome", "/usr/bin/google-chrome-stable", "/opt/google/chrome/product_logo_32.xpm" },
    { "google earth", "/usr/bin/google-earth", "/opt/google/earth/free/product_logo_32.xpm" },
    { "konqueror", "/usr/bin/konqueror", "/usr/share/icons/hicolor/48x48/apps/konqueror.png" },
    { "mumble", "/usr/bin/mumble", "/usr/share/icons/hicolor/scalable/apps/mumble.svg" },
    { "opera", "/usr/bin/opera", "/usr/share/pixmaps/opera.xpm" },
    { "pidgin", "/usr/bin/pidgin", "/usr/share/icons/hicolor/48x48/apps/pidgin.png" },
    { "seamonkey", "seamonkey", "/usr/share/pixmaps/seamonkey.png" },
    { "skype", "skype", "/usr/share/icons/hicolor/48x48/apps/skype.png" },
    { "thunderbird", "/usr/bin/thunderbird", "/usr/share/icons/hicolor/48x48/apps/thunderbird.png" },
    { "tor browser", "/usr/bin/tor-browser", "/usr/share/pixmaps/tor-browser.png" },
    { "vivaldi", "/usr/bin/vivaldi-stable", "/usr/share/icons/hicolor/48x48/apps/vivaldi.png" },
}
multimediamenu = {
    { "alsamixer", terminal.." -e alsamixer", "/usr/share/icons/hicolor/48x48/categories/applications-other.png" },
    { "audacity", "/usr/bin/audacity", "/usr/share/icons/hicolor/48x48/apps/audacity.png" },
    { "brasero", "/usr/bin/brasero ", "/usr/share/icons/hicolor/48x48/apps/brasero.png" },
    { "cmus", terminal.." -e cmus", "/usr/share/icons/hicolor/48x48/categories/applications-other.png" },
    { "kaffeine", "/usr/bin/kaffeine", "/usr/share/icons/hicolor/scalable/apps/kaffeine.svg" },
    { "spotify", "/usr/bin/spotify", "/usr/share/pixmaps/spotify-client.png" },
    { "vlc", "/usr/bin/vlc", "/usr/share/icons/hicolor/48x48/apps/vlc.png" },
    { "xfce4 mixer", "/usr/bin/xfce4-mixer", "/usr/share/icons/Adwaita/48x48/apps/multimedia-volume-control.png" },
}
officemenu = {
    { "acrobat reader", "/usr/bin/acroread", "/usr/share/pixmaps/acroread.png" },
    { "dia", "/usr/bin/dia", "/usr/share/icons/hicolor/48x48/apps/dia.png" },
    { "epdfview", "/usr/bin/epdfview", "/usr/share/icons/hicolor/48x48/apps/epdfview.png" },
    { "gnucash", "/home/hanez/bin/gnucash", "/usr/share/icons/hicolor/48x48/apps/gnucash-icon.png" },
    { "hibiscus", "/usr/bin/jameica", "/opt/jameica/plugins/hibiscus/icons/hibiscus-icon-32x32.png" },
    { "libreoffice base", "/usr/bin/libreoffice --base", "/usr/share/icons/hicolor/48x48/apps/libreoffice-base.png" },
    { "libreoffice calc", "/usr/bin/libreoffice --calc", "/usr/share/icons/hicolor/48x48/apps/libreoffice-calc.png" },
    { "libreoffice draw", "/usr/bin/libreoffice --draw", "/usr/share/icons/hicolor/48x48/apps/libreoffice-draw.png" },
    { "libreoffice impress", "/usr/bin/libreoffice --impress", "/usr/share/icons/hicolor/48x48/apps/libreoffice-impress.png" },
    { "libreoffice math", "/usr/bin/libreoffice --math", "/usr/share/icons/hicolor/48x48/apps/libreoffice-math.png" },
    { "libreoffice writer", "/usr/bin/libreoffice --writer", "/usr/share/icons/hicolor/48x48/apps/libreoffice-writer.png" },
    { "pdfshuffler", "/usr/bin/pdfshuffler", "/usr/share/pixmaps/pdfshuffler.png" },
}
othermenu = {
    { "apache directory studio", "/usr/bin/apachedirectorystudio", "/opt/ApacheDirectoryStudio/icon.xpm" },
    { "soapui", "/usr/bin/soapui", "/usr/share/icons/hicolor/48x48/apps/soapui.png" },
}
radiomenu = {
    { "cubicsdr", "/usr/bin/cubicsdr", "/usr/share/cubicsdr/CubicSDR.png" },
    { "gnuradio", "/usr/bin/gnuradio-companion", "/usr/share/gnuradio/grc/freedesktop/grc-icon-48.png" },
    { "gqrx", "/usr/bin/gqrx", "/usr/share/pixmaps/gqrx.svg" },
    { "pothos", "/usr/bin/PothosGui", "/usr/share/Pothos/Desktop/pothos-gui-48.png" },
    { "urh", "/usr/bin/urh", "/usr/share/pixmaps/urh.png" },
}
sciencemenu = {
    { "cantor", "/usr/bin/cantor", "/usr/share/icons/hicolor/48x48/apps/cantor.png" },
    { "octave", "/usr/bin/octave --force-gui", "/usr/share/icons/hicolor/48x48/apps/octave.png" },
    { "stellarium", "/usr/bin/stellarium", "/usr/share/icons/hicolor/48x48/apps/stellarium.png" },
}
systemmenu = {
    { "appearance", "/usr/bin/lxappearance", "/usr/share/icons/Adwaita/48x48/categories/preferences-desktop.png" },
    { "bitdefender", "/usr/bin/bdgui", "/opt/BitDefender-scanner/share/doc/examples/icons/hicolor/48x48/apps/bitdefender.png" },
    { "gparted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/48x48/apps/gparted.png" },
    { "hardinfo", "hardinfo", "/usr/share/hardinfo/pixmaps/logo.png" },
    { "gufw", "/usr/bin/gufw", "/usr/share/icons/hicolor/scalable/apps/gufw.svg" },
    { "virt-manager", "/usr/bin/virt-manager", "/usr/share/icons/hicolor/48x48/apps/virt-manager.png" },
    { "virtualbox", "/usr/bin/virtualbox", "/usr/share/pixmaps/VBox.png" },
    { "wireshark", "/usr/bin/wireshark", "/usr/share/icons/hicolor/48x48/apps/wireshark.png" },
}
utilitiesmenu = {
    { "arandr", "/usr/bin/arandr", "/usr/share/icons/hicolor/scalable/devices/video-television.svg" },
    { "bluetooth", "/usr/bin/blueman-manager", "/usr/share/icons/hicolor/48x48/apps/blueman.png" },
    { "qsshfs", "/usr/bin/qsshfs", "/usr/share/icons/hicolor/32x32/apps/qsshfs.png" },
    { "unetbootin", "/usr/bin/unetbootin_polkit", "/usr/share/icons/hicolor/48x48/apps/unetbootin.png" },
}
mymainmenu = awful.menu({ items = {
    { "accessories", accessoriesmenu, beautiful.icon_path.."categories/applications-accessories.png" },
    { "database", dbmenu, "/usr/share/icons/oxygen/base/48x48/places/server-database.png" },
    { "development", developmentmenu, beautiful.icon_path.."categories/applications-development.png" },
    { "engineering", engineeringmenu, beautiful.icon_path.."categories/applications-engineering.png" },
    { "games", gamesmenu, beautiful.icon_path.."categories/applications-games.png" },
    { "graphics", graphicsmenu, beautiful.icon_path.."categories/applications-graphics.png" },
    { "internet", internetmenu, beautiful.icon_path.."categories/applications-internet.png" },
    { "multimedia", multimediamenu, beautiful.icon_path.."categories/applications-multimedia.png" },
    { "office", officemenu, beautiful.icon_path.."categories/applications-office.png" },
    { "other", othermenu, beautiful.icon_path.."categories/applications-other.png" },
    { "radio", radiomenu, "/usr/share/icons/matefaenza/apps/48/radio.png" },
    { "science", sciencemenu, beautiful.icon_path.."categories/applications-science.png" },
    { "system", systemmenu, beautiful.icon_path.."categories/applications-system.png" },
    { "utilities", utilitiesmenu, beautiful.icon_path.."categories/applications-utilities.png" },
    { "filemanager", "/usr/bin/thunar", beautiful.icon_path.."apps/system-file-manager.png" },
    { "terminal", terminal, beautiful.icon_path.."apps/utilities-terminal.png" },
    { "configuration", editor_cmd .. " " .. awesome.conffile, beautiful.icon_path.."categories/preferences-other.png" },
    { "reload", awesome.restart, beautiful.icon_path.."actions/view-refresh.png" },
    { "quit", function () awesome.quit() end, beautiful.icon_path.."actions/system-log-out.png" }
  }
})
